### ISSUE TITLE
error in the application of the options 'status'

### ISSUE THREAD

**Issue by alegent** [idiv-biodiversity/lcvplants#18]
there is an error in the application of the options 'status' (True/False) and 'infraspecies_tab' (True/False). Not sure, but we should investigate the entry: 'stringsAsFactors = FALSE'.

**Comment by azizka** [comment]
the naming of these option was a bit unclear, we have now changed this to "synonyms" and infra_specific". There is however still a problem with the fuzzy matching and infra-specific values. We are working on this, for now, the LCVP function with default values should work fine (max_distance = 0)

**Comment by azizka** [comment]
This was a bug related to a previous update of the list. Fixed now, the status and infra-specific should now work without problems.
