### ISSUE TITLE
wrong execution in returning a double results from the function LCVPsolver

### ISSUE THREAD

**Issue by alegent** [idiv-biodiversity/lcvplants#19]
there is a wrong execution in returning a doble results from the function LCVPsolver to the main function LCVP. the output csv has repeated same results having the same id number
[LCVP_wrong_results.xlsx](https://github.com/idiv-biodiversity/lcvplants/files/5546299/LCVP_wrong_results.xlsx)

**Comment by azizka** [comment]
I could not reproduce this. It seems to me this is more a problem on the input side.

**Comment by rachaelholmes** [comment]
Hey thank you for uploading that an lodging the issue but there has been a mistake. The file you uploaded was my manually edited output after I got back to many results and infraspecies so I went through myself. 

Attached here is a short version of the input and output data with the code I used.

[lcvp_malesia_fuzzymatch_1_script.txt](https://github.com/idiv-biodiversity/lcvplants/files/5546683/lcvp_malesia_fuzzymatch_1_script.txt)

[taxon_order_orig_github.xlsx](https://github.com/idiv-biodiversity/lcvplants/files/5546688/taxon_order_orig_github.xlsx)
[lcvp_malesia_out1_github.xlsx](https://github.com/idiv-biodiversity/lcvplants/files/5546692/lcvp_malesia_out1_github.xlsx)

Thanks for the help and let me know if you need any more information.

**Comment by azizka** [comment]
This should work now, related to a previous update of LCVP. Please try again.
