### ISSUE TITLE
The synonyms and infra-specific arguments do not work if an authority is provided

### ISSUE THREAD

**Issue by azizka** [idiv-biodiversity/lcvplants#24]
If an authority name is provided, the LCVP function currently returns also synonyms and infra-specific names, irrespective of the synonyms and infra_specific settings provided by the user. These options should also work when an authority is provided.

**Comment by alegent** [comment]
Solved fixing the max.distance = 3 by default in the application of the fuzzy match algorithm to the autority when a taxa is provided of it.
