### ISSUE TITLE
Increase amount of species processed at a time: max amount species 58

### ISSUE THREAD

**Issue by anniezell** [idiv-biodiversity/lcvplants#26]
Out of the 100 species in this csv file I submitted, LCVP maxed out at 58 species and said this:
[ reached 'max' / getOption("max.print") -- omitted 41 rows ]

Is there any way I can do about 500 species at a time?

**Comment by alegent** [comment]
yes, if you use the options 'save = TRUE' and 'out_path = to/your/path', you can save the output into a csv file.
