### ISSUE TITLE
Deprecate v1 functions

### ISSUE THREAD

**Issue by azizka** [idiv-biodiversity/lcvplants#37]
update lcvplants 1 with messages that functions will soon be deprecated. In v2 add old functions as deprecated, to return relevant message to the user and point to the new alternative

**Comment by BrunoVilela** [comment]
They were defunct instead of deprecated, because they are no longer compatible with these version. An error is outputted indicating the alternative (if any), and help files for this functions are linked to lcvplants-defunct, that also has the link to the older release.
