### ISSUE TITLE
lcvp_join assertion

### ISSUE THREAD

**Issue by azizka** [idiv-biodiversity/lcvplants#47]
something is wrong with the lcvp_join assertion for data frames:

```
dat <- lcvp_join(x = as.data.frame(features), 
                 y = epi,
                 sp_columns = c("species", "merger"),
                 type = "left")

```

> Error: y should be a data.frame, not 'data.frame'. 

also, it should accept tibbles and tbl_df objects

>Error: x should be a data.frame, not 'tbl_df'.x should be a data.frame, not 'tbl'.x should be a data.frame, not 'data.frame'.
In addition: Warning messages:

>

**Comment by BrunoVilela** [comment]
Hey Alex, could send me the object features used?
