### ISSUE TITLE
Explicit dependency on LCVP package

### ISSUE THREAD

**Issue by Rekyt** [idiv-biodiversity/lcvplants#48]
Hey,
I've updated `lcvplants` to the last version to see if it worked on my special case.
I wanted to use `lcvplants::lcvp_match()` but got the following error:

> `Erreur : 'lcvp_sps_class' is not an exported object from 'namespace:LCVP'`

This is due to `LCVP` having been updated, but not reinstalled when I ran `remotes::install_github()` initially.
You could solve this issue by add a `Remotes:` field in the `DESCRIPTION` file as suggested in the [`devtools` vignette](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html)

This will be a concern if you plan to release `lcvplants` to CRAN but could fix the issue for now. Or you could also add `LCVP` as an explicit dependency that needs to be of minimum version.

**Comment by BrunoVilela** [comment]
Thanks for the feedback Matthias! Indeed that was in the initial plan, I just fixed this. It is now dependent on a  LCVP 2.0 or higher.
