### ISSUE TITLE
trouble installing LCVP on Mac OS 

### ISSUE THREAD

**Issue by sjevelazco** [idiv-biodiversity/lcvplants#49]
Hi 
I'm having some trouble installing LCVP on Mac OS operating systems. 

Downloading GitHub repo idiv-biodiversity/LCVP@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/idiv-biodiversity/LCVP/tarball/HEAD' failed

Thanks

**Comment by Apiaceae** [comment]
it's highly possible that you need to increase web response time by setting: options(timeout=9999999) to download data from github since the LCVP include a large data sets.

**Comment by BrunoVilela** [comment]
Closing this issue as there seems to be no problem with the new versions installations of LCVP and lcvplants in any OS so far. If this still happens, please let us know.
